#
R=c(1-1/6,1-1/6,1-1/6,1-1/6,1-1/6,1-1/6)
R_network_1=R[1]*R[6]*(1-(1-R[2])*(1-R[5])*(1-(1-(1-R[3])*(1-R[4]))))
print(R_network_1)
hazardrate=-log(R_network_1)
cat("hazard rate for system")
print(hazardrate)
cat("Reliability for 5 month")
R=exp(-hazardrate*5)
print(R)
cat("hazard rate for one item")
hazardrate=-log(1-1/6)
print(hazardrate)
cat("Reliability for 1 item in 5 month")
R=exp(-hazardrate*5)
print(R)
cat("Reliability for system in 5 month")
R=c(R,R,R,R,R,R)
R_network_5=R[1]*R[6]*(1-(1-R[2])*(1-R[5])*(1-(1-(1-R[3])*(1-R[4]))))
print(R_network_5)
